### ISSUE TITLE
No sound on avs_max98357a

### ISSUE THREAD

**Issue by foxrus** [thesofproject/avs-topology-xml#12] opened 2023-03-03 09:21 UTC
Hello! Will Apollo Lake support sound? My chromebook shows the following -

chronos@localhost / $ aplay -l **** List of PLAYBACK Hardware Devices **** card 0: avsmax98357a [avs_max98357a], device 1: Built-in Speakers (*) [] Subdevices: 1/1 Subdevice #0: subdevice #0 card 2: avsda7219 [avs_da7219], device 1: Headset (*) [] Subdevices: 1/1 Subdevice #0: subdevice #0 card 3: hdaudioB0D2 [hdaudioB0D2], device 1: HDMI1 (*) [] Subdevices: 1/1 Subdevice #0: subdevice #0 card 3: hdaudioB0D2 [hdaudioB0D2], device 2: HDMI2 (*) [] Subdevices: 1/1 Subdevice #0: subdevice #0 card 3: hdaudioB0D2 [hdaudioB0D2], device 3: HDMI3 (*) [] Subdevices: 1/1 Subdevice #0: subdevice #0

But when I run any linux-based operating system, I have no sound at all

**Comment by crojewsk-intel** [comment] 2023-03-03 16:17
Thanks for your report. APL-based Chromebooks had and continue having sound support. It would be quite irresponsible to ship configuration without a working audio.

Your description of the problem is too generic. Try to be more specific - attaching full logs for example can help with that. The fragment you pasted here does not help much.

When attaching full logs, please also state the OS you're reproducing problem on and model of your device. It's possible that you are missing some of the files in /lib/firmware after changing or upgrading your OS.

**Comment by foxrus** [comment] 2023-03-04 14:34
Yes, I use manjaro kde and linux 6.1 kernel. 
Here is the output of some commands

    ~  aplay -l                                                                                       ✔ 
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

What else can I tell you?

**Comment by crojewsk-intel** [comment] 2023-03-06 11:36
Output of `aplay -l` is not what I've asked for. Please refer to [Do's when submitting a ticket](https://gist.github.com/crojewsk/4e6382bfb0dbfaaf60513174211f29cb#dos-when-filing-a-ticket) and attach the required information here.

**Comment by foxrus** [comment] 2023-03-06 17:14
[log.txt](https://github.com/thesofproject/avs-topology-xml/files/10900686/log.txt)

uname -r
6.1.12-1-MANJARO

cat /sys/firmware/acpi/tables/NLHT > ~/nhlt.dat                                                ✔ 
cat: /sys/firmware/acpi/tables/NLHT: No such file or directory

[alsa-info.txt](https://github.com/thesofproject/avs-topology-xml/files/10900731/alsa-info.txt)


lsmod | grep snd                                                                  ✔  3m 3s  
snd_sof_pci_intel_apl    16384  0
snd_sof_intel_hda_common   221184  1 snd_sof_pci_intel_apl
soundwire_intel        57344  1 snd_sof_intel_hda_common
snd_sof_intel_hda      20480  1 snd_sof_intel_hda_common
snd_sof_pci            24576  2 snd_sof_intel_hda_common,snd_sof_pci_intel_apl
snd_sof_xtensa_dsp     20480  1 snd_sof_intel_hda_common
snd_sof               339968  2 snd_sof_pci,snd_sof_intel_hda_common
snd_sof_utils          20480  1 snd_sof
snd_soc_avs           172032  0
snd_soc_hda_codec      28672  1 snd_soc_avs
snd_soc_skl           217088  0
snd_soc_hdac_hda       28672  2 snd_sof_intel_hda_common,snd_soc_skl
snd_hda_ext_core       36864  5 snd_soc_avs,snd_soc_hda_codec,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_skl
snd_soc_sst_ipc        20480  1 snd_soc_skl
snd_soc_sst_dsp        40960  1 snd_soc_skl
snd_soc_acpi_intel_match    69632  3 snd_sof_intel_hda_common,snd_soc_skl,snd_sof_pci_intel_apl
snd_soc_acpi           16384  3 snd_soc_acpi_intel_match,snd_sof_intel_hda_common,snd_soc_skl
snd_hda_codec_hdmi     86016  1
snd_hda_intel          61440  1
snd_intel_dspcfg       36864  5 snd_soc_avs,snd_hda_intel,snd_sof,snd_sof_intel_hda_common,snd_soc_skl
snd_intel_sdw_acpi     20480  2 snd_sof_intel_hda_common,snd_intel_dspcfg
snd_soc_max98357a      20480  0
snd_soc_da7219         90112  0
snd_hda_codec         188416  7 snd_soc_avs,snd_hda_codec_hdmi,snd_soc_hda_codec,snd_hda_intel,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
snd_soc_core          393216  9 snd_soc_avs,snd_soc_hda_codec,snd_soc_da7219,soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_max98357a,snd_soc_skl
snd_hda_core          118784  10 snd_soc_avs,snd_hda_codec_hdmi,snd_soc_hda_codec,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
snd_compress           28672  1 snd_soc_core
ac97_bus               16384  1 snd_soc_core
snd_hwdep              16384  1 snd_hda_codec
snd_pcm_dmaengine      16384  1 snd_soc_core
snd_pcm               172032  14 snd_soc_avs,snd_hda_codec_hdmi,snd_hda_intel,snd_soc_da7219,snd_hda_codec,soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_compress,snd_soc_core,snd_sof_utils,snd_soc_skl,snd_hda_core,snd_pcm_dmaengine
snd_timer              49152  1 snd_pcm
snd                   131072  11 snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_pcm
soundcore              16384  1 snd


I guess I haven't forgotten anything

**Comment by crojewsk-intel** [comment] 2023-03-06 18:16
The select driver on your machine is: `snd_hda_intel` i.e.: HDAudio driver for non-AudioDSP usecases. max98357a and da7219 are not HDAudio codecs, these are I2S codecs. To have a working audio on APL-based device with v4.19+ kernel with those codecs onboard you need the avs-driver: `snd_soc_avs`.

The avs-driver is not a default yet, so you need to perform the selection yourself:
```
options snd_intel_dspcfg dsp_driver=4
```
within /etc/modprobe.d/. However, judging by the output from 'cat' regarding NHLT, you have no NHLT table present. Without it, audio over I2S interface won't work. You can at least try to enumerate the stack but it seems when you moved away from ChromeOS so did some of the crucial files.

**Comment by foxrus** [comment] 2023-03-06 18:35
Yes, I created the alsa-base.conf file in /etc/modprobe.d/ and added the line - options snd_intel_dspcfg dsp_driver=4
but after rebooting the system, I have no sound.
Is there anything else I can do to make my sound work?

**Comment by foxrus** [comment] 2023-03-06 18:41
And now when I type the command in the terminal - 
aplay -l                                                                        
aplay: device_list:274: no soundcards found...

**Comment by crojewsk-intel** [comment] 2023-03-06 22:22
> And now when I type the command in the terminal - aplay -l aplay: device_list:274: no soundcards found...

That's to be expected - please read my previous comment.

We can help each other here - attach the requested information ([Do's when submitting a ticket](https://gist.github.com/crojewsk/4e6382bfb0dbfaaf60513174211f29cb#dos-when-filing-a-ticket)) each time you change something plus describe _exactly_ what did you change. Also, please avoid double posting unless absolutely necessary.

**Comment by WeirdTreeThing** [comment] 2023-03-06 22:48
> However, judging by the output from 'cat' regarding NHLT, you have no NHLT table present. 

They actually just spelled NHLT wrong so I would assume they do have an NHLT table.

**Comment by foxrus** [comment] 2023-03-07 06:45
Okay, I'm sorry.
[log.txt](https://github.com/thesofproject/avs-topology-xml/files/10906195/log.txt)
[alsa-info.txt](https://github.com/thesofproject/avs-topology-xml/files/10906208/alsa-info.txt)


lsmod | grep snd                                                                               ✔ 
snd_sof_pci_intel_apl    16384  0
snd_sof_intel_hda_common   221184  1 snd_sof_pci_intel_apl
soundwire_intel        57344  1 snd_sof_intel_hda_common
snd_sof_intel_hda      20480  1 snd_sof_intel_hda_common
snd_sof_pci            24576  2 snd_sof_intel_hda_common,snd_sof_pci_intel_apl
snd_sof_xtensa_dsp     20480  1 snd_sof_intel_hda_common
snd_sof               339968  2 snd_sof_pci,snd_sof_intel_hda_common
snd_sof_utils          20480  1 snd_sof
snd_hda_codec_hdmi     86016  0
snd_soc_avs           172032  0
snd_soc_hda_codec      28672  1 snd_soc_avs
snd_soc_skl           217088  0
snd_soc_hdac_hda       28672  2 snd_sof_intel_hda_common,snd_soc_skl
snd_hda_ext_core       36864  5 snd_soc_avs,snd_soc_hda_codec,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_skl
snd_soc_sst_ipc        20480  1 snd_soc_skl
snd_soc_sst_dsp        40960  1 snd_soc_skl
snd_soc_acpi_intel_match    69632  3 snd_sof_intel_hda_common,snd_soc_skl,snd_sof_pci_intel_apl
snd_soc_acpi           16384  3 snd_soc_acpi_intel_match,snd_sof_intel_hda_common,snd_soc_skl
snd_hda_intel          61440  0
snd_intel_dspcfg       36864  5 snd_soc_avs,snd_hda_intel,snd_sof,snd_sof_intel_hda_common,snd_soc_skl
snd_intel_sdw_acpi     20480  2 snd_sof_intel_hda_common,snd_intel_dspcfg
snd_soc_da7219         90112  0
snd_soc_max98357a      20480  0
snd_hda_codec         188416  7 snd_soc_avs,snd_hda_codec_hdmi,snd_soc_hda_codec,snd_hda_intel,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
snd_soc_core          393216  9 snd_soc_avs,snd_soc_hda_codec,snd_soc_da7219,soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_max98357a,snd_soc_skl
snd_compress           28672  1 snd_soc_core
snd_hda_core          118784  10 snd_soc_avs,snd_hda_codec_hdmi,snd_soc_hda_codec,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
ac97_bus               16384  1 snd_soc_core
snd_hwdep              16384  1 snd_hda_codec
snd_pcm_dmaengine      16384  1 snd_soc_core
snd_pcm               172032  14 snd_soc_avs,snd_hda_codec_hdmi,snd_hda_intel,snd_soc_da7219,snd_hda_codec,soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_compress,snd_soc_core,snd_sof_utils,snd_soc_skl,snd_hda_core,snd_pcm_dmaengine
snd_timer              49152  1 snd_pcm
snd                   131072  9 snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_pcm
soundcore              16384  1 snd

**Comment by crojewsk-intel** [comment] 2023-03-07 08:13
@WeirdTreeThing good catch. That's one problem less.

@foxrus You're missing some crucial files indeed:
```
[   13.928532] snd_soc_avs 0000:00:0e.0: Direct firmware load for intel/avs/apl/dsp_basefw.bin failed with error -2
[   13.928547] snd_soc_avs 0000:00:0e.0: request firmware failed: -2
[   13.928553] snd_soc_avs 0000:00:0e.0: firmware boot failed: -2
```
Error `-2` tells us that the file is missing. Firmware files are publicly available at [linux-firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/intel/avs). Please copy them into relevant directory on your machine - make sure the structure of directories stays the same as in linux-firmware to avoid any future '-2' errors.

One thing that bothers me - in your initial comment, at the very top of this thread you pasted:
```
chronos@localhost / $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: avsmax98357a [avs_max98357a], device 1: Built-in Speakers () [] Subdevices: 1/1 Subdevice #0: subdevice #0
card 2: avsda7219 [avs_da7219], device 1: Headset () [] Subdevices: 1/1 Subdevice #0: subdevice #0
```
what clearly shows that something did enumerate back then. Almost like this was taken from a different configuration - with ChromeOS installed perhaps? The firmware files had to be in place for sound cards to show up.

**Comment by foxrus** [comment] 2023-03-07 09:14
> @WeirdTreeThing good catch. That's one problem less.
> 
> @foxrus You're missing some crucial files indeed:
> 
> ```
> [   13.928532] snd_soc_avs 0000:00:0e.0: Direct firmware load for intel/avs/apl/dsp_basefw.bin failed with error -2
> [   13.928547] snd_soc_avs 0000:00:0e.0: request firmware failed: -2
> [   13.928553] snd_soc_avs 0000:00:0e.0: firmware boot failed: -2
> ```
> 
> Error `-2` tells us that the file is missing. Firmware files are publicly available at [linux-firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/intel/avs). Please copy them into relevant directory on your machine - make sure the structure of directories stays the same as in linux-firmware to avoid any future '-2' errors.
> 
> One thing that bothers me - in your initial comment, at the very top of this thread you pasted:
> 
> ```
> chronos@localhost / $ aplay -l
> **** List of PLAYBACK Hardware Devices ****
> card 0: avsmax98357a [avs_max98357a], device 1: Built-in Speakers () [] Subdevices: 1/1 Subdevice #0: subdevice #0
> card 2: avsda7219 [avs_da7219], device 1: Headset () [] Subdevices: 1/1 Subdevice #0: subdevice #0
> ```
> 
> what clearly shows that something did enumerate back then. Almost like this was taken from a different configuration - with ChromeOS installed perhaps? The firmware files had to be in place for sound cards to show up.

Should I copy these files to /root/intel/? or /lib/firmware/intel/?

**Comment by foxrus** [comment] 2023-03-07 09:22
Should I copy these files to /root/intel/? or /lib/firmware/intel/?

**Comment by crojewsk-intel** [comment] 2023-03-07 09:22
On most linux distros these files reside in `/lib/firmware/` - that's the top-level directory for all firmware files. Line from your previous log tells us the rest of the story:
```
[   13.928532] snd_soc_avs 0000:00:0e.0: Direct firmware load for intel/avs/apl/dsp_basefw.bin failed with error -2
```
so, on APL-based machines the avs-driver is searching for `/lib/firmware/intel/avs/apl/dsp_basefw.bin`. That's the full path for the file.

**Comment by foxrus** [comment] 2023-03-07 09:34
I copied the files, but after rebooting the system, I have no sound

[alsa-info.txt](https://github.com/thesofproject/avs-topology-xml/files/10907914/alsa-info.txt)
[log.txt](https://github.com/thesofproject/avs-topology-xml/files/10907919/log.txt)

**Comment by crojewsk-intel** [comment] 2023-03-07 09:50
There are quite a few of steps ahead of us. "I have no sound" will remain with us until those are complete. No need to repeat that.

Could you provide an output of `ls -la /lib/firmware/intel/avs/apl` and `tree /lib/firmware/intel/avs`?

**Comment by foxrus** [comment] 2023-03-07 09:53
ls -la /lib/firmware/intel/avs/apl                                                             ✔ 
total 3292
drwxr-xr-x 2 fox  fox     4096 бер  7 11:07 .
drwxr-xr-x 3 root root    4096 бер  7 11:28 ..
-rw-r--r-- 1 fox  fox  3358780 бер  7 11:06 dsp_basefw.bin

**Comment by foxrus** [comment] 2023-03-07 09:55
tree /lib/firmware/intel/avs                                                            ✔  7s  
zsh: correct 'tree' to 'tee' [nyae]? n
/lib/firmware/intel/avs
└── apl
    └── dsp_basefw.bin

2 directories, 1 file

**Comment by crojewsk-intel** [comment] 2023-03-07 10:03
Please avoid double posting. Otherwise I'll have to moderate this thread. It's good to keep other readers in mind. Someone reading this weeks or months from now will find it easier if replies are well formatted.

Forgotten to ask about the md5sum but guess it does not matter now - somehow you copied an incorrect file.
```
ls -la /lib/firmware/intel/avs/apl

-rw-r--r-- 1 crojewsk crojewsk 505632 lut 15 10:16 dsp_basefw.bin
```
See the difference? 3358780 on yours versus 505632 on the official linux-firmware repo.
Output of md5sum for completeness sake:
```
md5sum /lib/firmware/intel/avs/apl/dsp_basefw.bin
16205c5d01ef1d68aacab0dd7336440d  /lib/firmware/intel/avs/apl/dsp_basefw.bin
```

**Comment by foxrus** [comment] 2023-03-07 10:34
I apologize. I downloaded the file again, and restarted the computer, here are the files

[alsa-info.txt](https://github.com/thesofproject/avs-topology-xml/files/10908402/alsa-info.txt)
[log.txt](https://github.com/thesofproject/avs-topology-xml/files/10908403/log.txt)

ls -la /lib/firmware/intel/avs/apl                                                             ✔ 
total 504
drwxr-xr-x 2 fox fox   4096 бер  7 12:22 .
drwxr-xr-x 5 fox fox   4096 бер  7 12:22 ..
-rw-r--r-- 1 fox fox 505632 бер  7 12:22 dsp_basefw.bin
    ~  tree /lib/firmware/intel/avs                                                                   ✔ 
/lib/firmware/intel/avs
├── apl
│   └── dsp_basefw.bin
├── cnl
│   └── dsp_basefw.bin
└── skl
    ├── dsp_basefw.bin
    └── dsp_mod_7CAD0808-AB10-CD23-EF45-12AB34CD56EF.bin

4 directories, 4 files

**Comment by crojewsk-intel** [comment] 2023-03-07 10:47
Key fragment:
```
[   19.035318] snd_soc_avs 0000:00:0e.0: bad FW version 9.22.3.4908, expected 9.22.1.4323 or newer
[   19.035332] snd_soc_avs 0000:00:0e.0: invalid firmware data: -22
[   19.035366] snd_soc_avs 0000:00:0e.0: firmware boot failed: -22
```
which I'm actually sorry for. This is an unforeseen side effect of recent changes in our CI/CD and integration infrastructure. I see now that one of the version numbers is mistakenly pointing to '3' rather than '1'.

Let's try with:
```
options snd_soc_avs ignore_fw_version=1
```
Do that within /etc/modprobe.d/, let it be part of one of .conf files you have been editing earlier.

**Comment by foxrus** [comment] 2023-03-07 11:52
Yes, I replaced the line in the file
[alsa-info.txt](https://github.com/thesofproject/avs-topology-xml/files/10908998/alsa-info.txt)
[log.txt](https://github.com/thesofproject/avs-topology-xml/files/10909000/log.txt)

**Comment by crojewsk-intel** [comment] 2023-03-07 12:16
Why did you remove the `options snd_intel_dspcfg dsp_driver=4` line? Logs show that you've reverted back to `snd_hda_intel`.

**Comment by foxrus** [comment] 2023-03-07 12:26
I thought I needed to replace the line, but now I added another line
[alsa-info.txt](https://github.com/thesofproject/avs-topology-xml/files/10909305/alsa-info.txt)
[log.txt](https://github.com/thesofproject/avs-topology-xml/files/10909307/log.txt)

**Comment by crojewsk-intel** [comment] 2023-03-07 12:40
Nice! AudioDSP is loading nicely. It seems my suspicions were correct - you're all missing all the /lib/firmware/ audio files after transitioning away from ChromeOS.

Topology files for da7219 and max98357a I2S codec devices are part in this very project (i2s/ subdirectory). avstplg tool used to compile these is part of [avsdk](https://github.com/thesofproject/avsdk).

**Comment by foxrus** [comment] 2023-03-07 12:45
I still don't understand what I have to do. 
How could I have lost my audio files if I just installed Manjaro alongside ChromeOS?
Can I copy some files from Chrome OS?

**Comment by foxrus** [comment] 2023-03-07 13:33
I don't understand how to use avstplg

**Comment by crojewsk-intel** [comment] 2023-03-09 20:02
Snappy is officially supported up to v5.10 kernel with ChromeOS. If I'm not mistaken, skylake-driver configuration was supported there up to v4.19. I know not how your /lib/firmware ended up like this but it's clear you're missing some crucial files when compared to Snappy with ChromeOS under v5.10.

Now, in regard to avstplg - did you read avsdk/README plus its [building instructions](https://github.com/thesofproject/avsdk#building)? avstplg CLI is very similar to alsatplg one. The later should be already installed on your machine.

[Overview](https://github.com/thesofproject/avs-topology-xml#overview) uncovers most secrets.
```
avstplg  -c my_tplg.xml  -o my_tplg.conf   # Intel's XML audio topology descriptor into ALSA friendly (userspace) format (UCM)
alsatplg -c my_tplg.conf -o my_tplg.bin    # ALSA friendly (userspace) format (UCM) into ALSA (kernel) friendly binary
```
Topology binaries shall be then moved to /lib/firmware/intel/avs/ directory.

**Comment by foxrus** [comment] 2023-03-10 08:30
Thank you for your response. Yes, I read it, but I didn't understand how to install it. I have installed msbuild mono from the official Archlinux repository, and then what should I do?

**Comment by crojewsk-intel** [comment] 2023-03-10 09:05
Hmm.. Have you ever cloned a repo? I thought it's obvious but perhaps you are unfamiliar with 'git'. Attaching topology files that should cover all codec devices on your machine: [snappy_topologies.zip](https://github.com/thesofproject/avs-topology-xml/files/10940351/snappy_topologies.zip).

**Comment by foxrus** [comment] 2023-03-10 09:21
Thank you for the files. It's much easier this way.
I copied the files but there is no sound
[alsa-info.txt](https://github.com/thesofproject/avs-topology-xml/files/10940500/alsa-info.txt)
[log.txt](https://github.com/thesofproject/avs-topology-xml/files/10940504/log.txt)

**Comment by crojewsk-intel** [comment] 2023-03-10 10:34
From the logs it looks like devices: HDMI and da7219 (headset) enumerated properly. DMIC won't because your kernel is missing [\[PATCH 0/4\] Add support for DSP volume controls](https://lore.kernel.org/all/20221214185500.3896902-1-amadeuszx.slawinski@linux.intel.com/) series - it's part of v6.2 kernel and onward. You would have to backport them, build the kernel and install it yourself. The process is not as easy as building audio topology binary and is outside of the scope of this ticket. There's plenty documentation available online how to prepare a kernel image by yourself.

max98357a on the other hand, is not enumerating at all. The codec device does not output anything in the logs. As the machine board driver (snd_soc_avs_max98357a) has nothing to talk to (snd_soc_max98357a), the endpoint is not functional. Perhaps the device is damaged?

It'd be good if you had the official ChromeOS image with v5.10 kernel for Snappy available as a backup and cross check every time you do a change on your machine.

**Comment by foxrus** [comment] 2023-03-10 10:40
I have the ChromeOS operating system installed, and the sound works great on it.

**Comment by no2spam** [comment] 2023-09-02 12:28
Hi @foxrus 

Try @WeirdTreeThing script to fix audio from [https://github.com/WeirdTreeThing/chromebook-linux-audio](https://github.com/WeirdTreeThing/chromebook-linux-audio) .

Thanks to @WeirdTreeThing script i have a working sound on my Acer Chromebook Spin 11 R751T using AVS driver.


uname -a
`Linux electro 6.4.12-artix1-1 #1 SMP PREEMPT_DYNAMIC Fri, 25 Aug 2023 13:07:12 +0000 x86_64 GNU/Linux`

aplay -l
`**** List of PLAYBACK Hardware Devices ****
card 0: avsmax98357a [avs_max98357a], device 1: Built-in Speakers (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: hdaudioB0D2 [hdaudioB0D2], device 1: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: hdaudioB0D2 [hdaudioB0D2], device 2: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: hdaudioB0D2 [hdaudioB0D2], device 3: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: avsda7219 [avs_da7219], device 1: Headset (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`

**Comment by crojewsk-intel** [comment] 2023-09-04 08:05
As the relevant kernel changes are already part of the Linus' tree, closing the subject. If something new pops up, please open a new ticket.

**Closed as completed by crojewsk-intel** 2023-09-04 08:05 UTC
